services:
  music:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - mynetwork
    environment:
      - NGINX_RELOAD_ENABLED=true
networks:
  mynetwork:
    name: mynetwork
    external: true
